// This is the proto buffer file for the WordSearcher
// Server configuration.
// It uses Mongo Atlas as a DB level and will be called
// by an Angular client.

// Protocol Buffer 3

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: wspb/ws.proto

// package and options

package wordsearcher

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Verse
type Verse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Book     int32  `protobuf:"varint,1,opt,name=book,proto3" json:"book,omitempty"`
	BookName string `protobuf:"bytes,2,opt,name=bookName,proto3" json:"bookName,omitempty"`
	Chapter  int32  `protobuf:"varint,3,opt,name=chapter,proto3" json:"chapter,omitempty"`
	Verse    int32  `protobuf:"varint,4,opt,name=verse,proto3" json:"verse,omitempty"`
	Text     string `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	Keywords string `protobuf:"bytes,6,opt,name=keywords,proto3" json:"keywords,omitempty"`
}

func (x *Verse) Reset() {
	*x = Verse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wspb_ws_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Verse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Verse) ProtoMessage() {}

func (x *Verse) ProtoReflect() protoreflect.Message {
	mi := &file_wspb_ws_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Verse.ProtoReflect.Descriptor instead.
func (*Verse) Descriptor() ([]byte, []int) {
	return file_wspb_ws_proto_rawDescGZIP(), []int{0}
}

func (x *Verse) GetBook() int32 {
	if x != nil {
		return x.Book
	}
	return 0
}

func (x *Verse) GetBookName() string {
	if x != nil {
		return x.BookName
	}
	return ""
}

func (x *Verse) GetChapter() int32 {
	if x != nil {
		return x.Chapter
	}
	return 0
}

func (x *Verse) GetVerse() int32 {
	if x != nil {
		return x.Verse
	}
	return 0
}

func (x *Verse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Verse) GetKeywords() string {
	if x != nil {
		return x.Keywords
	}
	return ""
}

type VerseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Book       int32 `protobuf:"varint,1,opt,name=book,proto3" json:"book,omitempty"`
	Chapter    int32 `protobuf:"varint,2,opt,name=chapter,proto3" json:"chapter,omitempty"`
	VerseStart int32 `protobuf:"varint,3,opt,name=verse_start,json=verseStart,proto3" json:"verse_start,omitempty"`
	VerseEnd   int32 `protobuf:"varint,4,opt,name=verse_end,json=verseEnd,proto3" json:"verse_end,omitempty"`
}

func (x *VerseRequest) Reset() {
	*x = VerseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wspb_ws_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerseRequest) ProtoMessage() {}

func (x *VerseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wspb_ws_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerseRequest.ProtoReflect.Descriptor instead.
func (*VerseRequest) Descriptor() ([]byte, []int) {
	return file_wspb_ws_proto_rawDescGZIP(), []int{1}
}

func (x *VerseRequest) GetBook() int32 {
	if x != nil {
		return x.Book
	}
	return 0
}

func (x *VerseRequest) GetChapter() int32 {
	if x != nil {
		return x.Chapter
	}
	return 0
}

func (x *VerseRequest) GetVerseStart() int32 {
	if x != nil {
		return x.VerseStart
	}
	return 0
}

func (x *VerseRequest) GetVerseEnd() int32 {
	if x != nil {
		return x.VerseEnd
	}
	return 0
}

type VerseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Verses []*Verse `protobuf:"bytes,1,rep,name=verses,proto3" json:"verses,omitempty"`
}

func (x *VerseResponse) Reset() {
	*x = VerseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wspb_ws_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerseResponse) ProtoMessage() {}

func (x *VerseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wspb_ws_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerseResponse.ProtoReflect.Descriptor instead.
func (*VerseResponse) Descriptor() ([]byte, []int) {
	return file_wspb_ws_proto_rawDescGZIP(), []int{2}
}

func (x *VerseResponse) GetVerses() []*Verse {
	if x != nil {
		return x.Verses
	}
	return nil
}

// Bible Plan
type BiblePlan struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Number int32    `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Days   []string `protobuf:"bytes,3,rep,name=days,proto3" json:"days,omitempty"`
}

func (x *BiblePlan) Reset() {
	*x = BiblePlan{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wspb_ws_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BiblePlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BiblePlan) ProtoMessage() {}

func (x *BiblePlan) ProtoReflect() protoreflect.Message {
	mi := &file_wspb_ws_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BiblePlan.ProtoReflect.Descriptor instead.
func (*BiblePlan) Descriptor() ([]byte, []int) {
	return file_wspb_ws_proto_rawDescGZIP(), []int{3}
}

func (x *BiblePlan) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BiblePlan) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *BiblePlan) GetDays() []string {
	if x != nil {
		return x.Days
	}
	return nil
}

type BiblePlanRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *BiblePlanRequest) Reset() {
	*x = BiblePlanRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wspb_ws_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BiblePlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BiblePlanRequest) ProtoMessage() {}

func (x *BiblePlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wspb_ws_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BiblePlanRequest.ProtoReflect.Descriptor instead.
func (*BiblePlanRequest) Descriptor() ([]byte, []int) {
	return file_wspb_ws_proto_rawDescGZIP(), []int{4}
}

func (x *BiblePlanRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type BiblePlanResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BiblePlan []*BiblePlan `protobuf:"bytes,1,rep,name=bible_plan,json=biblePlan,proto3" json:"bible_plan,omitempty"`
}

func (x *BiblePlanResponse) Reset() {
	*x = BiblePlanResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wspb_ws_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BiblePlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BiblePlanResponse) ProtoMessage() {}

func (x *BiblePlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wspb_ws_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BiblePlanResponse.ProtoReflect.Descriptor instead.
func (*BiblePlanResponse) Descriptor() ([]byte, []int) {
	return file_wspb_ws_proto_rawDescGZIP(), []int{5}
}

func (x *BiblePlanResponse) GetBiblePlan() []*BiblePlan {
	if x != nil {
		return x.BiblePlan
	}
	return nil
}

type BiblePlanDay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Reading1 string `protobuf:"bytes,2,opt,name=reading1,proto3" json:"reading1,omitempty"`
	Reading2 string `protobuf:"bytes,3,opt,name=reading2,proto3" json:"reading2,omitempty"`
	Reading3 string `protobuf:"bytes,4,opt,name=reading3,proto3" json:"reading3,omitempty"`
	Reading4 string `protobuf:"bytes,5,opt,name=reading4,proto3" json:"reading4,omitempty"`
}

func (x *BiblePlanDay) Reset() {
	*x = BiblePlanDay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wspb_ws_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BiblePlanDay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BiblePlanDay) ProtoMessage() {}

func (x *BiblePlanDay) ProtoReflect() protoreflect.Message {
	mi := &file_wspb_ws_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BiblePlanDay.ProtoReflect.Descriptor instead.
func (*BiblePlanDay) Descriptor() ([]byte, []int) {
	return file_wspb_ws_proto_rawDescGZIP(), []int{6}
}

func (x *BiblePlanDay) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BiblePlanDay) GetReading1() string {
	if x != nil {
		return x.Reading1
	}
	return ""
}

func (x *BiblePlanDay) GetReading2() string {
	if x != nil {
		return x.Reading2
	}
	return ""
}

func (x *BiblePlanDay) GetReading3() string {
	if x != nil {
		return x.Reading3
	}
	return ""
}

func (x *BiblePlanDay) GetReading4() string {
	if x != nil {
		return x.Reading4
	}
	return ""
}

type BiblePlanDayRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Day  int32  `protobuf:"varint,2,opt,name=day,proto3" json:"day,omitempty"`
}

func (x *BiblePlanDayRequest) Reset() {
	*x = BiblePlanDayRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wspb_ws_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BiblePlanDayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BiblePlanDayRequest) ProtoMessage() {}

func (x *BiblePlanDayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wspb_ws_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BiblePlanDayRequest.ProtoReflect.Descriptor instead.
func (*BiblePlanDayRequest) Descriptor() ([]byte, []int) {
	return file_wspb_ws_proto_rawDescGZIP(), []int{7}
}

func (x *BiblePlanDayRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BiblePlanDayRequest) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

type BiblePlanDayResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Day *BiblePlanDay `protobuf:"bytes,1,opt,name=day,proto3" json:"day,omitempty"`
}

func (x *BiblePlanDayResponse) Reset() {
	*x = BiblePlanDayResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wspb_ws_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BiblePlanDayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BiblePlanDayResponse) ProtoMessage() {}

func (x *BiblePlanDayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wspb_ws_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BiblePlanDayResponse.ProtoReflect.Descriptor instead.
func (*BiblePlanDayResponse) Descriptor() ([]byte, []int) {
	return file_wspb_ws_proto_rawDescGZIP(), []int{8}
}

func (x *BiblePlanDayResponse) GetDay() *BiblePlanDay {
	if x != nil {
		return x.Day
	}
	return nil
}

// Search
type SearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Term     string `protobuf:"bytes,1,opt,name=term,proto3" json:"term,omitempty"`
	Filter   string `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`     // search filter, i.e. in, or exact
	Location string `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"` // location of the search, default all, or nt (New Testament), ot, etc.
	Options  string `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`   // future options to add more complex and specific searches
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wspb_ws_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wspb_ws_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_wspb_ws_proto_rawDescGZIP(), []int{9}
}

func (x *SearchRequest) GetTerm() string {
	if x != nil {
		return x.Term
	}
	return ""
}

func (x *SearchRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *SearchRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *SearchRequest) GetOptions() string {
	if x != nil {
		return x.Options
	}
	return ""
}

// Custom requests
type BookRangeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start int32 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"` // beginning book number in the range of books
	End   int32 `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`     // ending book number, inclusive
}

func (x *BookRangeRequest) Reset() {
	*x = BookRangeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wspb_ws_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookRangeRequest) ProtoMessage() {}

func (x *BookRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wspb_ws_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookRangeRequest.ProtoReflect.Descriptor instead.
func (*BookRangeRequest) Descriptor() ([]byte, []int) {
	return file_wspb_ws_proto_rawDescGZIP(), []int{10}
}

func (x *BookRangeRequest) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *BookRangeRequest) GetEnd() int32 {
	if x != nil {
		return x.End
	}
	return 0
}

type ChapterRangeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Book  int32 `protobuf:"varint,1,opt,name=book,proto3" json:"book,omitempty"`   // book number
	Start int32 `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"` // start chapter in the given book
	End   int32 `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`     // end chapter
}

func (x *ChapterRangeRequest) Reset() {
	*x = ChapterRangeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wspb_ws_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChapterRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChapterRangeRequest) ProtoMessage() {}

func (x *ChapterRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wspb_ws_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChapterRangeRequest.ProtoReflect.Descriptor instead.
func (*ChapterRangeRequest) Descriptor() ([]byte, []int) {
	return file_wspb_ws_proto_rawDescGZIP(), []int{11}
}

func (x *ChapterRangeRequest) GetBook() int32 {
	if x != nil {
		return x.Book
	}
	return 0
}

func (x *ChapterRangeRequest) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *ChapterRangeRequest) GetEnd() int32 {
	if x != nil {
		return x.End
	}
	return 0
}

type CustomRange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type        string  `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Booknumber  int32   `protobuf:"varint,3,opt,name=booknumber,proto3" json:"booknumber,omitempty"`
	Customrange []int32 `protobuf:"varint,4,rep,packed,name=customrange,proto3" json:"customrange,omitempty"`
}

func (x *CustomRange) Reset() {
	*x = CustomRange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wspb_ws_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomRange) ProtoMessage() {}

func (x *CustomRange) ProtoReflect() protoreflect.Message {
	mi := &file_wspb_ws_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomRange.ProtoReflect.Descriptor instead.
func (*CustomRange) Descriptor() ([]byte, []int) {
	return file_wspb_ws_proto_rawDescGZIP(), []int{12}
}

func (x *CustomRange) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CustomRange) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CustomRange) GetBooknumber() int32 {
	if x != nil {
		return x.Booknumber
	}
	return 0
}

func (x *CustomRange) GetCustomrange() []int32 {
	if x != nil {
		return x.Customrange
	}
	return nil
}

type CustomRangeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CustomRangeRequest) Reset() {
	*x = CustomRangeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wspb_ws_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomRangeRequest) ProtoMessage() {}

func (x *CustomRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wspb_ws_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomRangeRequest.ProtoReflect.Descriptor instead.
func (*CustomRangeRequest) Descriptor() ([]byte, []int) {
	return file_wspb_ws_proto_rawDescGZIP(), []int{13}
}

func (x *CustomRangeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CustomRangeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomRange *CustomRange `protobuf:"bytes,1,opt,name=custom_range,json=customRange,proto3" json:"custom_range,omitempty"`
}

func (x *CustomRangeResponse) Reset() {
	*x = CustomRangeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wspb_ws_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomRangeResponse) ProtoMessage() {}

func (x *CustomRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wspb_ws_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomRangeResponse.ProtoReflect.Descriptor instead.
func (*CustomRangeResponse) Descriptor() ([]byte, []int) {
	return file_wspb_ws_proto_rawDescGZIP(), []int{14}
}

func (x *CustomRangeResponse) GetCustomRange() *CustomRange {
	if x != nil {
		return x.CustomRange
	}
	return nil
}

var File_wspb_ws_proto protoreflect.FileDescriptor

var file_wspb_ws_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x77, 0x73, 0x70, 0x62, 0x2f, 0x77, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0c, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x22, 0x97, 0x01,
	0x0a, 0x05, 0x56, 0x65, 0x72, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x62,
	0x6f, 0x6f, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62,
	0x6f, 0x6f, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x70, 0x74,
	0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65,
	0x72, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x65, 0x72, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x76, 0x65, 0x72, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6b,
	0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6b,
	0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x22, 0x7a, 0x0a, 0x0c, 0x56, 0x65, 0x72, 0x73, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x68,
	0x61, 0x70, 0x74, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x76, 0x65, 0x72, 0x73, 0x65, 0x5f, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x76, 0x65, 0x72, 0x73,
	0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x76, 0x65, 0x72, 0x73, 0x65, 0x5f,
	0x65, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x76, 0x65, 0x72, 0x73, 0x65,
	0x45, 0x6e, 0x64, 0x22, 0x3c, 0x0a, 0x0d, 0x56, 0x65, 0x72, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x06, 0x76, 0x65, 0x72, 0x73, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x65, 0x72, 0x2e, 0x56, 0x65, 0x72, 0x73, 0x65, 0x52, 0x06, 0x76, 0x65, 0x72, 0x73, 0x65,
	0x73, 0x22, 0x4b, 0x0a, 0x09, 0x42, 0x69, 0x62, 0x6c, 0x65, 0x50, 0x6c, 0x61, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x79, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x79, 0x73, 0x22, 0x26,
	0x0a, 0x10, 0x42, 0x69, 0x62, 0x6c, 0x65, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x4b, 0x0a, 0x11, 0x42, 0x69, 0x62, 0x6c, 0x65, 0x50,
	0x6c, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x0a, 0x62,
	0x69, 0x62, 0x6c, 0x65, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x42,
	0x69, 0x62, 0x6c, 0x65, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x09, 0x62, 0x69, 0x62, 0x6c, 0x65, 0x50,
	0x6c, 0x61, 0x6e, 0x22, 0x92, 0x01, 0x0a, 0x0c, 0x42, 0x69, 0x62, 0x6c, 0x65, 0x50, 0x6c, 0x61,
	0x6e, 0x44, 0x61, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x61, 0x64,
	0x69, 0x6e, 0x67, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x61, 0x64,
	0x69, 0x6e, 0x67, 0x31, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x32,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x32,
	0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x33, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x33, 0x12, 0x1a, 0x0a, 0x08,
	0x72, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x34, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x72, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x34, 0x22, 0x3b, 0x0a, 0x13, 0x42, 0x69, 0x62, 0x6c,
	0x65, 0x50, 0x6c, 0x61, 0x6e, 0x44, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x61, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x64, 0x61, 0x79, 0x22, 0x44, 0x0a, 0x14, 0x42, 0x69, 0x62, 0x6c, 0x65, 0x50, 0x6c,
	0x61, 0x6e, 0x44, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a,
	0x03, 0x64, 0x61, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x77, 0x6f, 0x72,
	0x64, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x42, 0x69, 0x62, 0x6c, 0x65, 0x50,
	0x6c, 0x61, 0x6e, 0x44, 0x61, 0x79, 0x52, 0x03, 0x64, 0x61, 0x79, 0x22, 0x71, 0x0a, 0x0d, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x65, 0x72, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x72, 0x6d,
	0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x3a,
	0x0a, 0x10, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x22, 0x51, 0x0a, 0x13, 0x43, 0x68,
	0x61, 0x70, 0x74, 0x65, 0x72, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65,
	0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x22, 0x77, 0x0a,
	0x0b, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x6f, 0x6f, 0x6b, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x62, 0x6f, 0x6f, 0x6b, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x72, 0x61,
	0x6e, 0x67, 0x65, 0x18, 0x04, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x22, 0x28, 0x0a, 0x12, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x53, 0x0a, 0x13, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x0c, 0x63, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x5f, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x77, 0x6f, 0x72, 0x64, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x43, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x52, 0x61, 0x6e, 0x67, 0x65, 0x32, 0xbc, 0x04, 0x0a, 0x13, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x42, 0x0a,
	0x05, 0x56, 0x65, 0x72, 0x73, 0x65, 0x12, 0x1a, 0x2e, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x56, 0x65, 0x72, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x65,
	0x72, 0x2e, 0x56, 0x65, 0x72, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x44, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x1b, 0x2e, 0x77, 0x6f,
	0x72, 0x64, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x77, 0x6f, 0x72, 0x64, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x56, 0x65, 0x72, 0x73, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x09, 0x42, 0x69, 0x62, 0x6c, 0x65,
	0x50, 0x6c, 0x61, 0x6e, 0x12, 0x1e, 0x2e, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x65, 0x72, 0x2e, 0x42, 0x69, 0x62, 0x6c, 0x65, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x65, 0x72, 0x2e, 0x42, 0x69, 0x62, 0x6c, 0x65, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x57, 0x0a, 0x0c, 0x42, 0x69, 0x62, 0x6c, 0x65,
	0x50, 0x6c, 0x61, 0x6e, 0x44, 0x61, 0x79, 0x12, 0x21, 0x2e, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x42, 0x69, 0x62, 0x6c, 0x65, 0x50, 0x6c, 0x61, 0x6e,
	0x44, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x77, 0x6f, 0x72,
	0x64, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x42, 0x69, 0x62, 0x6c, 0x65, 0x50,
	0x6c, 0x61, 0x6e, 0x44, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x4a, 0x0a, 0x09, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x1e, 0x2e,
	0x77, 0x6f, 0x72, 0x64, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x42, 0x6f, 0x6f,
	0x6b, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e,
	0x77, 0x6f, 0x72, 0x64, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x56, 0x65, 0x72,
	0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x0c,
	0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x21, 0x2e, 0x77,
	0x6f, 0x72, 0x64, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x61, 0x70,
	0x74, 0x65, 0x72, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1b, 0x2e, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x56,
	0x65, 0x72, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x54,
	0x0a, 0x0b, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x20, 0x2e,
	0x77, 0x6f, 0x72, 0x64, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x43, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x21, 0x2e, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x43,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x22, 0x5a, 0x20, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x65, 0x72, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x77, 0x6f, 0x72, 0x64,
	0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wspb_ws_proto_rawDescOnce sync.Once
	file_wspb_ws_proto_rawDescData = file_wspb_ws_proto_rawDesc
)

func file_wspb_ws_proto_rawDescGZIP() []byte {
	file_wspb_ws_proto_rawDescOnce.Do(func() {
		file_wspb_ws_proto_rawDescData = protoimpl.X.CompressGZIP(file_wspb_ws_proto_rawDescData)
	})
	return file_wspb_ws_proto_rawDescData
}

var file_wspb_ws_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_wspb_ws_proto_goTypes = []interface{}{
	(*Verse)(nil),                // 0: wordsearcher.Verse
	(*VerseRequest)(nil),         // 1: wordsearcher.VerseRequest
	(*VerseResponse)(nil),        // 2: wordsearcher.VerseResponse
	(*BiblePlan)(nil),            // 3: wordsearcher.BiblePlan
	(*BiblePlanRequest)(nil),     // 4: wordsearcher.BiblePlanRequest
	(*BiblePlanResponse)(nil),    // 5: wordsearcher.BiblePlanResponse
	(*BiblePlanDay)(nil),         // 6: wordsearcher.BiblePlanDay
	(*BiblePlanDayRequest)(nil),  // 7: wordsearcher.BiblePlanDayRequest
	(*BiblePlanDayResponse)(nil), // 8: wordsearcher.BiblePlanDayResponse
	(*SearchRequest)(nil),        // 9: wordsearcher.SearchRequest
	(*BookRangeRequest)(nil),     // 10: wordsearcher.BookRangeRequest
	(*ChapterRangeRequest)(nil),  // 11: wordsearcher.ChapterRangeRequest
	(*CustomRange)(nil),          // 12: wordsearcher.CustomRange
	(*CustomRangeRequest)(nil),   // 13: wordsearcher.CustomRangeRequest
	(*CustomRangeResponse)(nil),  // 14: wordsearcher.CustomRangeResponse
}
var file_wspb_ws_proto_depIdxs = []int32{
	0,  // 0: wordsearcher.VerseResponse.verses:type_name -> wordsearcher.Verse
	3,  // 1: wordsearcher.BiblePlanResponse.bible_plan:type_name -> wordsearcher.BiblePlan
	6,  // 2: wordsearcher.BiblePlanDayResponse.day:type_name -> wordsearcher.BiblePlanDay
	12, // 3: wordsearcher.CustomRangeResponse.custom_range:type_name -> wordsearcher.CustomRange
	1,  // 4: wordsearcher.WordsearcherService.Verse:input_type -> wordsearcher.VerseRequest
	9,  // 5: wordsearcher.WordsearcherService.Search:input_type -> wordsearcher.SearchRequest
	4,  // 6: wordsearcher.WordsearcherService.BiblePlan:input_type -> wordsearcher.BiblePlanRequest
	7,  // 7: wordsearcher.WordsearcherService.BiblePlanDay:input_type -> wordsearcher.BiblePlanDayRequest
	10, // 8: wordsearcher.WordsearcherService.BookRange:input_type -> wordsearcher.BookRangeRequest
	11, // 9: wordsearcher.WordsearcherService.ChapterRange:input_type -> wordsearcher.ChapterRangeRequest
	13, // 10: wordsearcher.WordsearcherService.CustomRange:input_type -> wordsearcher.CustomRangeRequest
	2,  // 11: wordsearcher.WordsearcherService.Verse:output_type -> wordsearcher.VerseResponse
	2,  // 12: wordsearcher.WordsearcherService.Search:output_type -> wordsearcher.VerseResponse
	5,  // 13: wordsearcher.WordsearcherService.BiblePlan:output_type -> wordsearcher.BiblePlanResponse
	8,  // 14: wordsearcher.WordsearcherService.BiblePlanDay:output_type -> wordsearcher.BiblePlanDayResponse
	2,  // 15: wordsearcher.WordsearcherService.BookRange:output_type -> wordsearcher.VerseResponse
	2,  // 16: wordsearcher.WordsearcherService.ChapterRange:output_type -> wordsearcher.VerseResponse
	14, // 17: wordsearcher.WordsearcherService.CustomRange:output_type -> wordsearcher.CustomRangeResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_wspb_ws_proto_init() }
func file_wspb_ws_proto_init() {
	if File_wspb_ws_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wspb_ws_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Verse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wspb_ws_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wspb_ws_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wspb_ws_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BiblePlan); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wspb_ws_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BiblePlanRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wspb_ws_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BiblePlanResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wspb_ws_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BiblePlanDay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wspb_ws_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BiblePlanDayRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wspb_ws_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BiblePlanDayResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wspb_ws_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wspb_ws_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookRangeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wspb_ws_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChapterRangeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wspb_ws_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomRange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wspb_ws_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomRangeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wspb_ws_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomRangeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wspb_ws_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wspb_ws_proto_goTypes,
		DependencyIndexes: file_wspb_ws_proto_depIdxs,
		MessageInfos:      file_wspb_ws_proto_msgTypes,
	}.Build()
	File_wspb_ws_proto = out.File
	file_wspb_ws_proto_rawDesc = nil
	file_wspb_ws_proto_goTypes = nil
	file_wspb_ws_proto_depIdxs = nil
}
